### ISSUE TITLE
SCSS support

### ISSUE THREAD

**Issue by jans-y** [impulse/gatsby-typescript-tailwind#82]
Hi,

Thank you for this starter. I think a lot of people would want to use SCSS so it would be a good idea to add a few tips to the Docs on how to do this. Since I am a beginner in Gatsby, it took me a while to make it work.

Thanks!

**Comment by impulse** [comment]
Hello there,

thanks for your suggestion but I think this would kind of defeat the purpose of Tailwind. There are definitely special use-cases like input styling where SASS/SCSS syntax would come in handy, but I think this is out of scope for a minimal starter template as there are also Tailwind plugins for such things.

I don't know what solution you came up with in the end but with postcss this easily doable:
https://github.com/postcss/postcss-nested
